import type { Language } from "@/types/content";

export type LocalizedLegal = Record<Language, string>;

export const LEGAL_BASE_URL = "https://artatlas.app";

export const legalUrls = {
  terms: `${LEGAL_BASE_URL}/legal/terms/`,
  eula: "https://www.apple.com/legal/internet-services/itunes/dev/stdeula/",
  privacy: `${LEGAL_BASE_URL}/legal/privacy/`,
  permissions: `${LEGAL_BASE_URL}/legal/privacy/`,
  account: `${LEGAL_BASE_URL}/legal/data-deletion/`,
  dataDeletion: `${LEGAL_BASE_URL}/legal/data-deletion/`,
  support: `${LEGAL_BASE_URL}/support/`
} as const;

export const legalTexts: Record<"terms" | "privacy" | "permissions", LocalizedLegal> = {
  terms: {
    tr: "Art Atlas, sanat tarihi ve sanat topluluğu odaklı bir uygulamadır. Uygulamayı kullanarak topluluk kurallarına, telif haklarına, diğer kullanıcılara ve platform politikalarına saygılı davranmayı kabul edersiniz. Keşfet paylaşımları, yorumlar, mesajlaşmalar, profil bilgileri, resim yarışması katılımları, quizler, beğeniler, favoriler ve destek talepleri kötüye kullanım, spam, taciz, nefret söylemi, telif ihlali ve yanıltıcı içerik açısından incelenebilir. Size ait olmayan görselleri veya izinsiz içerikleri yükleyemez, diğer kullanıcıları rahatsız edemez ya da güvenlik sistemlerini kötüye kullanamazsınız. Art Atlas; sakıncalı içerik, taciz, tehdit, nefret söylemi ve kötüye kullanıma karşı sıfır tolerans uygular. Kurallara aykırı içerikler kaldırılabilir, yarışma/sıralama hakları sınırlandırılabilir ve hesaplar moderasyon incelemesine alınabilir. Premium abonelikler ilgili uygulama mağazasının koşullarına tabidir. Destek ve hesap silme talepleri uygulama içinden veya resmi destek bağlantısından iletilebilir.",
    en: "Art Atlas is an art history and art community app. By using the app you agree to follow community rules, respect copyright, treat other members fairly, and comply with platform policies. Discover posts, comments, messages, profile details, painting contest entries, quizzes, likes, favorites, and support requests may be reviewed for abuse, spam, harassment, hate speech, copyright infringement, and misleading content. You may not upload content you do not own or have permission to use, harass other users, or abuse safety systems. Art Atlas has zero tolerance for objectionable content, harassment, threats, hate speech, and abuse. Content that violates rules may be removed, contest or ranking eligibility may be limited, and accounts may be reviewed by moderation. Premium subscriptions are governed by the applicable app marketplace terms. Support and account deletion requests can be submitted in the app or through the official support link.",
    ru: "Art Atlas — приложение об истории искусства и художественном сообществе. Используя приложение, вы соглашаетесь соблюдать правила сообщества, авторские права, уважать других пользователей и правила платформ. Публикации в Discover, комментарии, сообщения, профильные данные, работы для конкурса рисунков, викторины, лайки, избранное и обращения в поддержку могут проверяться на злоупотребления, спам, домогательства, ненависть, нарушения авторских прав и вводящий в заблуждение контент. Нельзя загружать чужой или неразрешенный контент, беспокоить пользователей или злоупотреблять системами безопасности. Art Atlas придерживается политики нулевой терпимости к неприемлемому контенту, домогательствам, угрозам, ненависти и злоупотреблениям. Нарушающий правила контент может быть удален, участие в конкурсах/рейтингах ограничено, аккаунты могут проходить модерацию. Premium-подписки регулируются условиями соответствующего магазина приложений. Запросы в поддержку и на удаление аккаунта можно отправить в приложении или через официальный канал поддержки.",
    uz: "Art Atlas sanʼat tarixi va sanʼat hamjamiyati ilovasidir. Ilovadan foydalanganda hamjamiyat qoidalari, mualliflik huquqi, boshqa foydalanuvchilar va platforma siyosatlariga hurmat bilan rioya qilishga rozilik bildirasiz. Discover postlari, izohlar, xabarlar, profil maʼlumotlari, rasm tanlovi ishlari, viktorinalar, yoqtirishlar, sevimlilar va yordam so‘rovlari suiisteʼmol, spam, taʼqib, nafrat, mualliflik huquqi buzilishi va chalg‘ituvchi kontent bo‘yicha tekshirilishi mumkin. Sizga tegishli bo‘lmagan yoki ruxsatsiz kontentni yuklash, boshqa foydalanuvchilarni bezovta qilish yoki xavfsizlik tizimlarini suiisteʼmol qilish mumkin emas. Art Atlas nomaqbul kontent, taʼqib, tahdid, nafrat va suiisteʼmolga nisbatan mutlaqo toqatsiz siyosat yuritadi. Qoidabuzar kontent o‘chirilishi, tanlov/reyting huquqlari cheklanishi va akkauntlar moderatsiya ko‘rigiga olinishi mumkin. Premium obunalar tegishli ilova do‘koni shartlariga bo‘ysunadi. Yordam va akkauntni o‘chirish so‘rovlari ilova ichidan yoki rasmiy yordam havolasi orqali yuboriladi."
  },
  privacy: {
    tr: "Art Atlas; hesap bilgileri, e-posta, profil fotoğrafı, biyografi, ülke/şehir, sosyal bağlantılar, kullanıcı tarafından yüklenen görseller, resim yarışması katılımları, keşfet paylaşımları, yorumlar, takip/engelleme bilgileri, mesajlaşma ayarları ve teslim/engelleme gibi sınırlı teknik sohbet durumları, beğeni, favori, okuma ve görüntüleme hareketleri, quiz/oyun skorları, sıralama verileri, bildirim tercihleri, reklam tercihleri ve destek taleplerini hizmeti sunmak, güvenliği sağlamak, kötüye kullanımı önlemek, moderasyon yapmak ve deneyimi geliştirmek için işler. Galeri ve kamera erişimi yalnızca sizin seçtiğiniz dosyalar için kullanılır; seçmediğiniz galeri içerikleri işlenmez. Yorumlar, keşfet paylaşımları ve yarışma içerikleri ilgili topluluk alanlarında görünebilir ve kurallara aykırı kullanım halinde moderasyon sürecine konu olabilir. Özel mesaj içerikleri topluluk alanı gibi yayınlanmaz ve rutin olarak incelenmez; yalnızca kullanıcı tarafından bildirilen bir konuşma, güvenlik ihlali, kötüye kullanım şüphesi, hesap güvenliği, yasal yükümlülük veya teknik teslim/silme süreci için gerekli olan sınırlı bilgiler değerlendirilir. Veriler güvenli bulut altyapısında saklanır. Sponsorlu içerik, AdMob reklamları ve ölçüm/analitik çözümleri platform izinleri ve tercihlerinize uygun şekilde kullanılabilir; premium üyeler reklamsız deneyim alabilir. Kişisel verilerinize erişim, düzeltme, dışa aktarma ve silme taleplerinizi uygulama içi hesap silme akışı, destek sayfası veya veri silme bağlantısı üzerinden iletebilirsiniz.",
    en: "Art Atlas processes account details, email, profile photo, biography, country/city, social links, user-uploaded images, painting contest entries, Discover posts, comments, follow/block data, messaging preferences and limited technical chat states such as delivery, blocking, or deletion status, likes, favorites, reading and view activity, quiz/game scores, ranking data, notification preferences, ad preferences, and support requests to provide the service, maintain security, prevent abuse, perform moderation, and improve the experience. Photo library and camera access are used only for files you select; gallery content you do not select is not processed. Comments, Discover posts, and contest content may appear in relevant community areas and may be subject to moderation when they violate rules. Private message content is not published as community content and is not routinely reviewed; only a user-reported conversation, safety incident, suspected abuse, account security issue, legal obligation, or technical delivery/deletion process may require limited related information to be evaluated. Data is stored on secure cloud infrastructure. Sponsored content, AdMob ads, and measurement/analytics solutions may be used in line with platform permissions and your preferences; premium members may receive an ad-free experience. You can request access, correction, export, or deletion through the in-app account deletion flow, Support, or the data deletion link.",
    ru: "Art Atlas обрабатывает данные аккаунта, e-mail, фото профиля, биографию, страну/город, социальные ссылки, загруженные изображения, работы конкурса рисунков, публикации Discover, комментарии, данные подписок/блокировок, настройки сообщений и ограниченные технические состояния чата, такие как доставка, блокировка или удаление, лайки, избранное, историю чтения и просмотров, результаты викторин/игр, рейтинги, настройки уведомлений, рекламные предпочтения и обращения в поддержку для предоставления сервиса, безопасности, предотвращения злоупотреблений, модерации и улучшения опыта. Галерея и камера используются только для выбранных вами файлов; невыбранные файлы галереи не обрабатываются. Комментарии, публикации Discover и конкурсный контент могут быть видны в соответствующих разделах сообщества и при нарушении правил могут проходить модерацию. Содержимое личных сообщений не публикуется как контент сообщества и не просматривается регулярно; только жалоба пользователя, инцидент безопасности, подозрение на злоупотребление, защита аккаунта, законная обязанность или технический процесс доставки/удаления могут требовать оценки ограниченной связанной информации. Данные хранятся в защищенной облачной инфраструктуре. Спонсорский контент, реклама AdMob и аналитика могут использоваться согласно разрешениям платформ и вашим настройкам; Premium может быть без рекламы. Запросы на доступ, исправление, экспорт или удаление данных можно отправить через удаление аккаунта в приложении, поддержку или ссылку удаления данных.",
    uz: "Art Atlas xizmatni taqdim etish, xavfsizlikni saqlash, suiisteʼmolning oldini olish, moderatsiya qilish va tajribani yaxshilash uchun akkaunt maʼlumotlari, e-pochta, profil rasmi, biografiya, davlat/shahar, ijtimoiy havolalar, foydalanuvchi yuklagan rasmlar, rasm tanlovi ishlari, Discover postlari, izohlar, kuzatish/bloklash maʼlumotlari, xabar sozlamalari hamda yetkazish, bloklash yoki o‘chirish holati kabi cheklangan texnik chat holatlari, yoqtirishlar, sevimlilar, o‘qish va ko‘rish faolligi, viktorina/o‘yin ballari, reyting maʼlumotlari, bildirishnoma sozlamalari, reklama tanlovlari va yordam so‘rovlarini qayta ishlaydi. Galereya va kamera faqat siz tanlagan fayllar uchun ishlatiladi; tanlanmagan galereya kontenti qayta ishlanmaydi. Izohlar, Discover postlari va tanlov kontenti tegishli hamjamiyat bo‘limlarida ko‘rinishi hamda qoidalar buzilganda moderatsiya jarayoniga kiritilishi mumkin. Shaxsiy xabar mazmuni hamjamiyat kontenti sifatida eʼlon qilinmaydi va odatiy tarzda ko‘rib chiqilmaydi; faqat foydalanuvchi xabar bergan suhbat, xavfsizlik hodisasi, suiisteʼmol gumoni, akkaunt xavfsizligi, qonuniy majburiyat yoki texnik yetkazish/o‘chirish jarayoni uchun zarur bo‘lgan cheklangan bog‘liq maʼlumotlar baholanishi mumkin. Maʼlumotlar xavfsiz bulut infratuzilmasida saqlanadi. Homiy kontent, AdMob reklamalari va tahlil yechimlari platforma ruxsatlari hamda sozlamalaringizga muvofiq ishlatilishi mumkin; premium aʼzolar reklamasiz tajriba olishi mumkin. Kirish, tuzatish, eksport yoki o‘chirish so‘rovlarini ilova ichidagi akkauntni o‘chirish, Yordam yoki maʼlumotlarni o‘chirish havolasi orqali yuborishingiz mumkin."
  },
  permissions: {
    tr: "Fotoğraf galerisi: profil fotoğrafı, topluluk eseri ve hikâye görselleri seçmek için kullanılır; yalnızca sizin seçtiğiniz dosyalar işlenir. Kamera (isteğe bağlı): doğrudan fotoğraf çekmek için kullanılabilir. Bildirimler: takip, beğeni, yarışma ve sistem duyuruları için tercihlerinize göre gönderilir. Reklam kimliği: kişiselleştirilmiş reklam tercihleri için platform izni istenebilir; reddedebilirsiniz.",
    en: "Photo library: used to choose profile photos, community artwork, and story images; only files you select are processed. Camera (optional): may be used to capture photos directly. Notifications: sent according to your preferences for follows, likes, contests, and system announcements. Advertising identifier: platform permission may be requested for personalized ads; you can decline.",
    ru: "Галерея: для выбора фото профиля, работ сообщества и историй; обрабатываются только выбранные вами файлы. Камера (опционально): для съёмки фото. Уведомления: отправляются согласно вашим настройкам. Рекламный идентификатор: для персонализированной рекламы может запрашиваться разрешение платформы; отказ возможен.",
    uz: "Foto galereya: profil rasmi, hamjamiyat asarlari va hikoya rasmlarini tanlash uchun ishlatiladi; faqat siz tanlagan fayllar qayta ishlanadi. Kamera (ixtiyoriy): to'g'ridan-to'g'ri rasm olish uchun. Bildirishnomalar: sozlamalaringizga ko'ra yuboriladi. Reklama identifikatori: shaxsiylashtirilgan reklama uchun platforma ruxsati so'ralishi mumkin; rad etishingiz mumkin."
  }
};

export function mergeStoreLegalTexts(subscriptionTerms: LocalizedLegal, permissions: LocalizedLegal) {
  return {
    ...legalTexts,
    permissions,
    terms: (Object.keys(legalTexts.terms) as (keyof LocalizedLegal)[]).reduce((copy, language) => ({
      ...copy,
      [language]: `${legalTexts.terms[language]}${subscriptionTerms[language]}`
    }), {} as LocalizedLegal)
  };
}

export const accountLegalTexts: LocalizedLegal = {
  tr: "Kullanıcı adı, e-posta, profil fotoğrafı, biyografi, ülke, şehir, sosyal medya bağlantıları, görünür profil içerikleri, keşfet paylaşımları, resim yarışması katılımları, yorumlar, mesajlaşma tercihleri, engelleme/silme gibi teknik sohbet durumları ve destek kayıtları hizmetin parçası olarak güvenli şekilde saklanabilir. Özel mesaj içerikleri herkese açık profil verisi sayılmaz. Hesabınızı kalıcı olarak silmek için Profil > Profili düzenle > Hesabımı sil yolunu kullanın. Ek veri erişim, dışa aktarma veya silme talepleri için Destek sayfasını ya da veri silme sayfasını ziyaret edin.",
  en: "Username, email, avatar, biography, country, city, social links, visible profile content, Discover posts, painting contest entries, comments, messaging preferences, technical chat states such as blocking/deletion status, and support records may be securely stored as part of the service. Private message content is not treated as public profile data. To permanently delete your account, open Profile > Edit profile > Delete my account. For additional access, export, or deletion requests, visit Support or the data deletion page.",
  ru: "Имя пользователя, e-mail, фото, биография, страна, город, социальные ссылки, видимый контент профиля, публикации Discover, работы конкурса рисунков, комментарии, настройки сообщений, технические состояния чата, такие как блокировка/удаление, и обращения в поддержку могут безопасно храниться как часть сервиса. Содержимое личных сообщений не считается публичными данными профиля. Для удаления аккаунта: Профиль > Редактировать > Удалить аккаунт. Дополнительные запросы на доступ, экспорт или удаление — через Поддержку или страницу удаления данных.",
  uz: "Foydalanuvchi nomi, e-pochta, avatar, biografiya, davlat, shahar, ijtimoiy havolalar, ko‘rinadigan profil kontenti, Discover postlari, rasm tanlovi ishlari, izohlar, xabar sozlamalari, bloklash/o‘chirish holati kabi texnik chat holatlari va yordam yozuvlari xizmatning bir qismi sifatida xavfsiz saqlanishi mumkin. Shaxsiy xabar mazmuni ommaviy profil maʼlumoti hisoblanmaydi. Akkauntni butunlay o‘chirish uchun Profil > Profilni tahrirlash > Hisobni o‘chirish yo‘lidan foydalaning. Qo‘shimcha kirish, eksport yoki o‘chirish so‘rovlari uchun Yordam yoki maʼlumotlarni o‘chirish sahifasiga kiring."
};

export const dataDeletionLegalTexts: LocalizedLegal = {
  tr: "Art Atlas hesabınızı uygulama içinden kalıcı olarak silebilirsiniz: Profil sekmesi > Profili düzenle > Hesabımı sil. Kimlik doğrulamasından sonra profiliniz, hesap bilgileriniz, keşfet paylaşımlarınız, yorumlarınız, beğenileriniz, favorileriniz, destek kayıtlarınız, yüklediğiniz görseller, resim yarışması katılımlarınız, quiz/oyun/sıralama verileriniz ve oturum bilgileriniz silinir veya anonimleştirilir. Özel sohbetlere ilişkin teslim, engelleme, silme durumu veya kullanıcı tarafından bildirilen sınırlı güvenlik kayıtları, kötüye kullanım incelemesi, hesap güvenliği, yasal yükümlülük veya uyuşmazlık çözümü için gerekli olduğu kadar korunabilir; topluluk içerikleri ise kurallara, diğer kullanıcıların görünürlüğüne ve teknik sınırlara göre bir süre görünür kalabilir. Uygulamayı kullanamıyorsanız https://artatlas.app/legal/data-deletion/ adresinden veya destek kanalından silme talebi gönderebilirsiniz.",
  en: "You can permanently delete your Art Atlas account in the app via Profile > Edit profile > Delete my account. After identity verification, your profile, account details, Discover posts, comments, likes, favorites, support records, uploaded images, painting contest entries, quiz/game/ranking data, and session data are deleted or anonymized. Limited technical chat states such as delivery, blocking, deletion status, or user-reported safety records may be kept only as needed for abuse review, account security, legal obligations, or dispute resolution; community content may remain visible for a limited time depending on rules, other users' visibility, and technical limits. If you cannot use the app, you can request deletion at https://artatlas.app/legal/data-deletion/ or through Support.",
  ru: "Вы можете навсегда удалить аккаунт Art Atlas в приложении: Профиль > Редактировать профиль > Удалить аккаунт. После подтверждения личности профиль, данные аккаунта, публикации Discover, комментарии, лайки, избранное, обращения в поддержку, загруженные изображения, работы конкурса рисунков, данные викторин/игр/рейтингов и сессии удаляются или анонимизируются. Ограниченные технические состояния личного чата, такие как доставка, блокировка, статус удаления или записи безопасности, отправленные пользователем в жалобе, могут храниться только при необходимости для проверки злоупотреблений, защиты аккаунта, законных обязанностей или споров; контент сообщества может ограниченное время оставаться видимым в зависимости от правил, видимости для других пользователей и технических ограничений. Если приложение недоступно, запрос можно отправить на https://artatlas.app/legal/data-deletion/ или через поддержку.",
  uz: "Art Atlas akkauntingizni ilova ichida Profil > Profilni tahrirlash > Hisobni o‘chirish orqali butunlay o‘chirishingiz mumkin. Shaxs tasdiqlangandan so‘ng profilingiz, akkaunt maʼlumotlari, Discover postlari, izohlar, yoqtirishlar, sevimlilar, yordam yozuvlari, yuklangan rasmlar, rasm tanlovi ishlari, viktorina/o‘yin/reyting maʼlumotlari va sessiya maʼlumotlari o‘chiriladi yoki anonimlashtiriladi. Yetkazish, bloklash, o‘chirish holati yoki foydalanuvchi tomonidan xabar qilingan xavfsizlik yozuvlari kabi shaxsiy chatga oid cheklangan texnik holatlar faqat suiisteʼmol tekshiruvi, akkaunt xavfsizligi, qonuniy majburiyatlar yoki nizolar uchun zarur bo‘lgan muddat saqlanishi mumkin; hamjamiyat kontenti esa qoidalar, boshqa foydalanuvchilardagi ko‘rinish va texnik cheklovlarga qarab cheklangan vaqt ko‘rinib turishi mumkin. Ilovadan foydalana olmasangiz, https://artatlas.app/legal/data-deletion/ yoki Yordam orqali so‘rov yuboring."
};

export const permissionUsageDescriptions = {
  photos: {
    tr: "Art Atlas, profil fotoğrafı ve sanat paylaşımları için galeriden görsel seçmenize izin verir.",
    en: "Art Atlas lets you choose images from your library for profile photos and art uploads.",
    ru: "Art Atlas позволяет выбирать изображения из галереи для профиля и публикаций.",
    uz: "Art Atlas profil rasmi va san'at yuklashlari uchun galereyadan rasm tanlashga imkon beradi."
  },
  camera: {
    tr: "Art Atlas, profil veya eser fotoğrafı çekmeniz için kameraya erişim ister.",
    en: "Art Atlas uses the camera so you can capture profile or artwork photos.",
    ru: "Art Atlas использует камеру для съёмки фото профиля или работ.",
    uz: "Art Atlas profil yoki asar rasmini olish uchun kameradan foydalanadi."
  },
  tracking: {
    tr: "Art Atlas, reklam deneyimini iyileştirmek için cihaz tanımlayıcısını kullanabilir. Bu izni reddedebilirsiniz.",
    en: "Art Atlas may use your device identifier to improve ad relevance. You can decline this permission.",
    ru: "Art Atlas может использовать идентификатор устройства для улучшения рекламы. Отказ возможен.",
    uz: "Art Atlas reklama tajribasini yaxshilash uchun qurilma identifikatoridan foydalanishi mumkin. Rad etishingiz mumkin."
  }
} as const;
